#include "Arkanoid.cpp"
#include "Arkanoid.cpp"
#include "Bejeweled.cpp"
#include "Doodle Jump.cpp"
#include "Fifteen-Puzzle.cpp"
#include "Mahjong.cpp"
#include "Minesweeper.cpp"
#include "NetWalk.cpp"
#include"Outrun.cpp"
#include "Racing.cpp"
#include "Tetris.cpp"
#include "Tron.cpp"
#include "Xonic.cpp"
#include "SFML/Graphics.hpp"
#include "time.h"
